### PR TITLE
allow custom action after URL is acquired

### PR DESCRIPTION
**Pull request by thehunmonkgroup**
adds urlAcquiredCallback key to config, which allows a custom
action to be performed via a callback function after a hangout
URL is acquired.

### CODE REVIEW

**Comment by yourcelf** [comment]
Not super stoked by this particular approach, though I appreciate the need -- putting a callback in the configuration file feels a bit hacky to me.  The only reason I made `conf.js` js instead of json is to make it easier to add explanatory comments.  My bad I guess; once it's code it's code, not data. :)

Instead of this PR, I've just pushed a commit that "library-ifies" the script so it can be required and called just like any other code.  You can manage your configuration and callbacks anyway you want.

For the use case in the PR here, you can now just create a new file to do your custom stuff like this:

```
#!/usr/bin/env node

var farmer = require("./index.js")
farmer.farmUrls(require("./conf.js"), function(err, url) {
    // do something with url or err
});
```

See the updated README for more on that.

**Comment by thehunmonkgroup** [comment]
oh yes, this is much better :)

tested and working on my end.

curious about one thing: it appears selenium is creating a new firefox
profile every time i run the script, as i have to 'allow and remember' the
plugin on each run. is there some trick you're using to have it use the
same profile? i did see in selenium where you can pass it a profile to use,
but i didn't see that in the script code.

**Comment by yourcelf** [comment]
I instantiate a new firefox profile which _should_ set the google talk plugins to always allow: https://github.com/unhangout/hangout-farmer/blob/master/index.js#L71-L76  It's possible that the plugins have different identifiers on different platforms and we might need to add a couple of names there.

What OS / firefox version are you using?

**Comment by thehunmonkgroup** [comment]
OS X 10.10, Firefox 45

**Comment by yourcelf** [comment]
Moving discussion to issue #2.

**Pull request closed without merging**
